import {Navigate,Route,Routes,useLocation,Outlet} from 'react-router-dom'
import {useAuth} from '../context/AuthContext'
import {AppShell} from '../components/layout'
import {Home,About,Features,HowItWorks,Contact} from '../pages/public'
import {Login,ForgotPassword,ResetPassword,ActivateAccount} from '../pages/auth'
import {Dashboard,ListPage,DetailPage,Analytics,Notifications,Profile,Settings,ScheduleLecture,StartLecture,MyClasses,MyStudents,LectureList,SummaryList,Forbidden} from '../pages/appPages'
import {roleHome} from '../services/authService'
function Protected({role,children}){const {user}=useAuth();const location=useLocation();if(!user)return <Navigate to="/login" replace state={{from:location.pathname}}/>;if(role&&user.role!==role)return <Forbidden/>;return <AppShell>{children ?? <Outlet/>}</AppShell>}
const roleRoutes=(role)=><Route path={`/${role}`} element={<Protected role={role}/>}>
<Route index element={<Navigate to={roleHome(role)} replace/>}/><Route path="dashboard" element={<Dashboard role={role}/>}/><Route path="profile" element={<Profile/>}/><Route path="settings" element={<Settings/>}/><Route path="notifications" element={<Notifications/>}/>
{role==='admin'&&<><Route path="teachers" element={<ListPage type="teachers" role={role}/>}/><Route path="teachers/:id" element={<DetailPage type="teachers" role={role}/>}/><Route path="students" element={<ListPage type="students" role={role}/>}/><Route path="students/:id" element={<DetailPage type="students" role={role}/>}/><Route path="classes" element={<ListPage type="classes" role={role}/>}/><Route path="classes/:id" element={<DetailPage type="classes" role={role}/>}/><Route path="lectures" element={<ListPage type="lectures" role={role}/>}/><Route path="lectures/:id" element={<DetailPage type="lectures" role={role}/>}/><Route path="summaries" element={<ListPage type="summaries" role={role}/>}/><Route path="summaries/:id" element={<DetailPage type="summaries" role={role}/>}/><Route path="analytics" element={<Analytics/>}/></>}
{role==='teacher'&&<><Route path="classes" element={<MyClasses role={role}/>}/><Route path="classes/:id" element={<DetailPage type="classes" role={role}/>}/><Route path="students" element={<MyStudents role={role}/>}/><Route path="students/:id" element={<DetailPage type="students" role={role}/>}/><Route path="schedule-lecture" element={<ScheduleLecture/>}/><Route path="lectures" element={<LectureList role={role}/>}/><Route path="lectures/:id" element={<DetailPage type="lectures" role={role}/>}/><Route path="lectures/:id/start" element={<StartLecture/>}/><Route path="summaries" element={<SummaryList role={role}/>}/><Route path="summaries/:id" element={<DetailPage type="summaries" role={role}/>}/></>}
{role==='student'&&<><Route path="classes" element={<MyClasses role={role}/>}/><Route path="classes/:id" element={<DetailPage type="classes" role={role}/>}/><Route path="lectures" element={<LectureList role={role} mode="upcoming"/>}/><Route path="lectures/:id" element={<DetailPage type="lectures" role={role}/>}/><Route path="history" element={<LectureList role={role} mode="history"/>}/><Route path="summaries" element={<SummaryList role={role}/>}/><Route path="summaries/:id" element={<DetailPage type="summaries" role={role}/>}/></>}
</Route>
export default function AppRoutes(){return <Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/features" element={<Features/>}/><Route path="/how-it-works" element={<HowItWorks/>}/><Route path="/contact" element={<Contact/>}/><Route path="/login" element={<Login/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/><Route path="/reset-password" element={<ResetPassword/>}/><Route path="/activate-account" element={<ActivateAccount/>}/>{roleRoutes('admin')}{roleRoutes('teacher')}{roleRoutes('student')}<Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
