import {useState} from 'react'
import {Check,ChevronDown,Loader2,Search,X,AlertCircle,Inbox,Copy,Download,Printer,MoreHorizontal} from 'lucide-react'
export const cn=(...x)=>x.filter(Boolean).join(' ')
export function Button({children,variant='primary',size='md',icon:Icon,loading=false,className='',...props}){const styles={primary:'bg-primary text-white shadow-claySm hover:-translate-y-0.5',secondary:'bg-white text-ink border border-slate-200 shadow-claySm hover:bg-slate-50 dark:bg-slate-800 dark:text-white dark:border-slate-700',ghost:'bg-transparent text-muted hover:text-primary hover:bg-blue-50/60 dark:hover:bg-slate-800',danger:'bg-red-50 text-red-600 hover:bg-red-100',soft:'bg-indigo-50 text-indigo-700 hover:bg-indigo-100'};return <button className={cn('inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary/30 disabled:opacity-50',size==='sm'?'px-3 py-2 text-xs':'px-4 py-2.5 text-sm',styles[variant],className)} disabled={loading||props.disabled} {...props}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:Icon&&<Icon className="h-4 w-4"/>}{children}</button>}
export function Card({children,className='',...props}){return <section className={cn('rounded-2xl border border-white/70 bg-white/90 shadow-clay dark:border-slate-700/80 dark:bg-slate-900/90',className)} {...props}>{children}</section>}
export function Badge({children,tone='neutral'}){const map={success:'bg-emerald-50 text-emerald-700',warning:'bg-amber-50 text-amber-700',danger:'bg-red-50 text-red-700',info:'bg-blue-50 text-blue-700',neutral:'bg-slate-100 text-slate-600',live:'bg-red-50 text-red-600'};return <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold',map[tone]||map.neutral)}>{children}</span>}
export function Avatar({initials='LF',size='md'}){return <div className={cn('grid place-items-center rounded-xl bg-indigo-50 font-bold text-indigo-600 dark:bg-indigo-950 dark:text-indigo-300',size==='lg'?'h-14 w-14 text-base':'h-9 w-9 text-xs')}>{initials}</div>}
export function PageHeader({title,description,actions}){return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-extrabold tracking-tight text-ink dark:text-white">{title}</h1>{description&&<p className="mt-1 text-sm text-muted">{description}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}
export function StatCard({label,value,trend,icon:Icon,tone='blue'}){return <Card className="p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p><p className="mt-2 text-2xl font-extrabold text-ink dark:text-white">{value}</p>{trend&&<p className="mt-1 text-xs font-semibold text-emerald-600">{trend}</p>}</div><div className={`rounded-xl p-3 ${tone==='green'?'bg-emerald-50 text-emerald-600':tone==='amber'?'bg-amber-50 text-amber-600':'bg-indigo-50 text-primary'}`}><Icon className="h-5 w-5"/></div></div></Card>}
export function SearchBar({value,onChange,placeholder='Search...'}){return <div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted"/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="input pl-9"/></div>}
export function Select({label,children,...props}){return <label className="block text-sm font-semibold text-ink dark:text-white">{label&&<span className="mb-1.5 block text-xs text-muted">{label}</span>}<select className="input" {...props}>{children}</select></label>}
export function Input({label,error, ...props}){return <label className="block text-sm font-semibold text-ink dark:text-white">{label&&<span className="mb-1.5 block text-xs text-muted">{label}</span>}<input className={cn('input',error&&'border-red-300')} {...props}/>{error&&<span className="mt-1 block text-xs text-red-600">{error}</span>}</label>}
export function Modal({open,onClose,title,children,footer}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><h3 className="font-bold text-ink dark:text-white">{title}</h3><button aria-label="Close" onClick={onClose} className="rounded-lg p-2 text-muted hover:bg-slate-100"><X className="h-4 w-4"/></button></div>{children}{footer&&<div className="mt-5 flex justify-end gap-2">{footer}</div>}</div></div>}
export function DataTable({columns,rows,empty='No records found.'}){return <div className="overflow-hidden rounded-2xl border border-slate-100 dark:border-slate-800"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50/80 dark:bg-slate-800/60"><tr>{columns.map(c=><th key={c.key} className="px-4 py-3 text-[11px] font-bold uppercase tracking-wide text-muted">{c.label}</th>)}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.length?rows.map((row,i)=><tr key={row.id||i} className="hover:bg-indigo-50/30 dark:hover:bg-slate-800/50">{columns.map(c=><td key={c.key} className="px-4 py-3 text-slate-700 dark:text-slate-200">{c.render?c.render(row):row[c.key]}</td>)}</tr>):<tr><td colSpan={columns.length} className="px-4 py-12 text-center text-muted">{empty}</td></tr>}</tbody></table></div></div>}
export function EmptyState({title='Nothing here yet',description='New activity will appear here when available.',action}){return <div className="grid place-items-center rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-10 text-center dark:border-slate-700 dark:bg-slate-800/40"><div className="mb-3 rounded-full bg-white p-3 shadow-claySm dark:bg-slate-900"><Inbox className="h-5 w-5 text-primary"/></div><h3 className="font-bold text-ink dark:text-white">{title}</h3><p className="mt-1 max-w-md text-sm text-muted">{description}</p>{action&&<div className="mt-4">{action}</div>}</div>}
export function ErrorState({onRetry}){return <div className="grid place-items-center rounded-2xl border border-red-100 bg-red-50/60 p-10 text-center"><AlertCircle className="mb-3 h-8 w-8 text-red-500"/><h3 className="font-bold text-red-800">Something went wrong</h3><p className="mt-1 text-sm text-red-600">We couldn't load this section.</p>{onRetry&&<Button className="mt-4" variant="danger" onClick={onRetry}>Try Again</Button>}</div>}
export function Skeleton({className=''}){return <div className={cn('animate-pulse rounded-xl bg-slate-200/70 dark:bg-slate-800',className)}/>}
export function ToastHost(){return null}
export function CopyButton({text}){const [copied,setCopied]=useState(false);return <Button size="sm" variant="secondary" icon={copied?Check:Copy} onClick={()=>{navigator.clipboard?.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1500)}}>{copied?'Copied':'Copy'}</Button>}
export const IconButton=({icon:Icon,...p})=><button className="rounded-xl p-2 text-muted hover:bg-slate-100 hover:text-primary dark:hover:bg-slate-800" {...p}><Icon className="h-4 w-4"/></button>
export {Download,Printer,MoreHorizontal,ChevronDown,Search}
